### ISSUE TITLE
错了几个字

### ISSUE THREAD

**Issue by 17337162621254271304** [piglei/one-python-craftsman#12]
def __enter__(self):
        # 刚方法将在进入上下文时调用
        return self

该方法将在进入上下文时调用  错了个字

还有前面几节举的例子, 列表的命名用 'l'(小写字母l), 看了半天, 觉得不应该啊.....  哈哈

**Comment by piglei** [comment]
感谢反馈，我晚点会修复下，你方便的话，也可以帮忙提个 PR 修下错字 :)

关于列表命名是这样的，有时候要虚拟一个片段代码作为样例来表达想法，但是缺少一种真实情景，所以其实起一些有意义的名字反而会增加读者的理解成本，因为这个例子里面，压根就没有所谓“情景”。

另外单字母变量也不是完全不行啦，在当前 context 比较小的情况下，特别短的名字也是完全可以接受的。（尤其是在我写了一段时间 Go 以后..）哈哈哈

**Comment by 17337162621254271304** [comment]
非常感谢你的回复.
可以提个pr
看了你的公众号没有赞赏, 老板也太大气了
如果和你一块写代码感觉肯定很爽

**Comment by piglei** [comment]
我早上顺手直接 fix 了，以后如果发现错字可以直接提 PR。
公众号没开赞赏，是因为开的晚，之前还没发够三篇原创，现在够了 😅。欢迎继续关注。

**Comment by 17337162621254271304** [comment]
1
