### ISSUE TITLE
更好的使用变量 - 2. 尽量不要用 globals()/locals() 中render的命名

### ISSUE THREAD

**Issue by MosesFu** [piglei/one-python-craftsman#13]
[更好的使用变量 - 2. 尽量不要用 globals()/locals()](https://github.com/piglei/one-python-craftsman/blob/master/zh_CN/1-using-variables-well.md#2-%E5%B0%BD%E9%87%8F%E4%B8%8D%E8%A6%81%E7%94%A8-globalslocals)

这里的代码示例

```py
def render(request, user_id, trip_id):
    pass
    return render(request, 'trip.html', locals())
```

上下两个render应该是对应不同的方法吧？使用相同的方法名是否有点不妥?

**Comment by piglei** [comment]
你好，谢谢你细心的阅读。这是个 Bug，我会修复下。😂
