### ISSUE TITLE
2.编写条件分支代码的技巧

### ISSUE THREAD

**Issue by leaicc** [piglei/one-python-craftsman#18]
```
if user.no_profile_exists:
    +++ profile_func = create_user_profile
    extra_args = {'points': 0, 'created': now()}
else:
    +++ profile_func = update_user_profile
    extra_args = {'updated': now()}

profile_func(
    username=user.username,
    email=user.email,
    age=user.age,
    address=user.address,
    **extra_args
)
```
你好，上面代码中我标记了 “+++” 的两行可以改成下面这样的吗？ 
```
create_user_profile = profile_func
update_user_profile = profile_func
```

**Comment by jackbai233** [comment]
> ```
> if user.no_profile_exists:
>     +++ profile_func = create_user_profile
>     extra_args = {'points': 0, 'created': now()}
> else:
>     +++ profile_func = update_user_profile
>     extra_args = {'updated': now()}
> 
> profile_func(
>     username=user.username,
>     email=user.email,
>     age=user.age,
>     address=user.address,
>     **extra_args
> )
> ```
> 
> 你好，上面代码中我标记了 “+++” 的两行可以改成下面这样的吗？
> 
> ```
> create_user_profile = profile_func
> update_user_profile = profile_func
> ```

这样肯定是不行的。**在python中函数也是一种对象，它能被赋值给变量，故调用该变量就是执行该函数**。感觉你对这个理解有些不清晰，具体可以看[廖雪峰的教程开头的例子](https://www.liaoxuefeng.com/wiki/1016959663602400/1017451662295584)。作者在这里是巧妙地通过给同一个变量赋予不同的值来执行了不同的函数

**Comment by piglei** [comment]
感谢帮忙解答，先 close 了 :)

**Comment by leaicc** [comment]
我理解的是：把函数赋值给变量，应该是 **变量=函数名**，如果是 **函数名=变量**，而变量之前并没有被定义，那不就报错了吗？

**Comment by Drinkey** [comment]
你的理解没有错，只是对代码可能有误解，`create_user_profile`和`update_user_profile`是实际被调用的函数，这里通过条件判断选择需要调用哪个函数，最后使用`profile_func`来调用选择要调用的函数。

**Comment by leaicc** [comment]
我在 Jupyter 里运行了一下，`profile_func = create_user_profile，profile_func = update_user_profile`和`create_user_profile = profile_func，update_user_profile = profile_func`的结果是一样的，但我还是感觉要写成后者那样，或者说这两种写法有什么不同吗？

**Comment by Drinkey** [comment]
扩展了一下原文里的代码，这样可能更容易理解一些。

只有`create_user_profile`和`update_user_profile`是实际实现功能的函数，在条件判断代码里，根据`user.no_profile_exists` 的值来判断是应该调用`create_user_profile`还是`update_user_profile`。此时，profile_func只是指向将要调用的一个函数的变量。

```python
def now():
    return 100

def create_user_profile(username, email, age, address, points, created):
    """ code to create a new user profile """
    print("creating user")

def update_user_profile(username, email, age, address, updated):
    """ code to update a existing user profile """
    print("updating user")

if True:
    profile_func = create_user_profile
    extra_args = {'points': 0, 'created': now()}
else:
    profile_func = update_user_profile
    extra_args = {'updated': now()}

# either create or update a user profile, no matter it already exists or not
profile_func(
    username='user.username',
    email='user.email',
    age='user.age',
    address='user.address',
    **extra_args
)
```

如果在你标出的位置使用`create_user_profile = profile_func`，`update_user_profile = profile_func`，此时profile_func根本不能存在，是不可能调到相应的函数的，会报错`NameError: name 'profile_func' is not defined`。

我在Jupyter里面也运行了，的确不会报错，但是也的确没有按照期望调用到相应的函数。原因是Jupyter的执行环境有上下文的，如果你先运行了正确的代码，再执行你的代码，实际上`profile_func`是在之前的上下文被定义了，所以执行结果一样吧。

贴了我测试的代码，你可以尝试在你想要修改的地方修改再运行试试，注意，我直接用了True/False来控制调用哪个函数，意思差不多。最好别用Jupyter，问题就很明确了。

**Comment by leaicc** [comment]
谢谢，明白了
