### ISSUE TITLE
能否分享一下您的个人PyCon 视频 TOP5

### ISSUE THREAD

**Issue by Jeffrey95** [piglei/one-python-craftsman#23]
首先感谢您分享高质量的文章。
刚刚去看了您分享的[ “Beyond PEP8 - Best practices for beautiful intelligible code”](https://www.youtube.com/watch?v=wf-BqAjZb8M)，也是受益匪浅。
不知道哪里可以找到您分享推荐的一些高质量的文章、视频等资料呢。

**Comment by piglei** [comment]
你好。

说起来有点不好意思，Top5 是我在写文章时，突然蹦出来的词。其实称之为 *“假如有 TOP 5，那么.. ...”* 更准确一点。到目前为止，我并没有真的给我看过的所有 PyCon 视频排过序。不过精彩的视频有很多，比如下面这些：

- [Loop like a native: while, for, iterators, generators - YouTube](https://www.youtube.com/watch?v=EnSu9hHGq5o&list=PLet0S8PtCvYVmdMSNW2A8UvejzoRaH9kK&index=13&t=860s)
- [Modern Dictionaries by Raymond Hettinger - YouTube](https://www.youtube.com/watch?v=p33CVV29OG8&list=PLet0S8PtCvYVmdMSNW2A8UvejzoRaH9kK&index=12&t=1460s)
- [Raymond Hettinger, Keynote on Concurrency, PyBay 2017 - YouTube](https://www.youtube.com/watch?v=9zinZmE3Ogk&list=PLet0S8PtCvYVmdMSNW2A8UvejzoRaH9kK&index=10&t=0s)

都值得一看。

我目前也没有专门整理自己推荐的文章、视频等资料。如果未来有机会能重新整理、优化一遍现在的系列文集，我可能会补全所有的参考资料。到那时再看看吧 :)
