### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by qixiangyang** [piglei/one-python-craftsman#27]
文章写的真好，获益匪浅。
感觉这个系列文章可以出一本书了~
另外问一下 写好面向对象代码的原则（下）什么时候更新
^ ^

**Comment by piglei** [comment]
你好，一篇比较长的文章一般得写两个星期左右（一个需要带娃的爸爸的极限业余效率）。

出书也不是没想过呢，不过得等写到 20 篇左右再 review 一遍所有的文章看看。
