### ISSUE TITLE
让class变得可调用？

### ISSUE THREAD

**Issue by yqNLP** [piglei/one-python-craftsman#28]
> 函数自然是“可被调用”的对象。但除了函数外，我们也可以让任何一个类（class）变得“可被调用”（callable）。办法很简单，只要自定义类的 __call__ 魔法方法即可。

类一直是可被调用的“callable”，这里是不是写错了，应该是object吧

**Comment by piglei** [comment]
感谢指出，原文措辞确实有些小问题。我觉得应该改成“类实例”比较好一些。

**Comment by yqNLP** [comment]
^_^

**Comment by piglei** [comment]
Fixed
