### ISSUE TITLE
err_msg未定义？

### ISSUE THREAD

**Issue by zbx91** [piglei/one-python-craftsman#30]
class CreateItemError(Exception):
    """创建 Item 失败时抛出的异常"""

def create_item(name):
    """创建一个新的 Item
    
    :raises: 当无法创建时抛出 CreateItemError
    """
    if len(name) > MAX_LENGTH_OF_NAME:
        raise CreateItemError('name of item is too long')
    if len(CURRENT_ITEMS) > MAX_ITEMS_QUOTA:
        raise CreateItemError('items is full')
    return Item(name=name)

def create_for_input():
    name = input()
    try:
        item = create_item(name)
    except CreateItemError as e:
        print(f'create item failed: {err_msg}') #这句是不是有bug，err_msg 无定义
    else:
        print(f'item<{name}> created')

**Comment by piglei** [comment]
应该是有点问题，我晚点会修复下。

**Comment by piglei** [comment]
已修复
