### ISSUE TITLE
第2篇好像有个bug

### ISSUE THREAD

**Issue by SoftDoggy** [piglei/one-python-craftsman#32]
https://github.com/piglei/one-python-craftsman/blob/master/zh_CN/2-if-else-block-secrets.md
第二篇里面的第四节，使用 try/while/for 中 else 分支，第一段函数里面，抛出异常的话应该就直接return了，怎么样都不会运行到do_the_second_thing()了吧。

**Comment by piglei** [comment]
`do_the_second_thing()` 应该是在未抛出异常时执行，不是抛出异常的时候。

**Comment by SoftDoggy** [comment]
既然只有未抛出异常的时候才会执行下去，为什么还要判断if first_thing_successed呢

**Comment by piglei** [comment]
在这段代码里面，确实是这样。😂
我觉得这段代码只适合作为 demo 理解，如果调整一下 except 里的逻辑可能会更好一些。
