### ISSUE TITLE
“value += 1” 并非线程安全

### ISSUE THREAD

**Issue by liutao1992** [piglei/one-python-craftsman#34]
你好，关于这个问题，我想请教一下，value在这里局部变量吗？

**Comment by piglei** [comment]
你好，value 是局部或是全部不是重点，重点在于 "+=" 运算符不是原子。在它的执行过程中有可能会被插入其他语句，所以不是线程安全的。

**Comment by ironboxer** [comment]
python3.10中的新变化:
https://stackoverflow.com/questions/69993959/python-threads-difference-for-3-10-and-others

demo:
```Python
from threading import Thread

i = 0

def foo():
    global i
    for _ in range(1000000):
        i += 1

def bar():
    global i
    for _ in range(1000000):
        i -= 1
    
threads = []    
for _ in range(10):
    thread = Thread(target=foo)
    threads.append(thread)
for _ in range(10):
    thread = Thread(target=bar)
    threads.append(thread)
 
for thread in threads:
    thread.start()

for thread in threads:
    thread.join()


print(i)
assert i == 0
```

我是认为，这从侧面说明“Python还不是一个很稳定的语言”，像这种特性，无论是否是原子的，早就应该固定下来，不发生变化。

**Comment by piglei** [comment]
> python3.10中的新变化: https://stackoverflow.com/questions/69993959/python-threads-difference-for-3-10-and-others
> 
> demo:
> 
> ```python
> from threading import Thread
> 
> i = 0
> 
> def foo():
>     global i
>     for _ in range(1000000):
>         i += 1
> 
> def bar():
>     global i
>     for _ in range(1000000):
>         i -= 1
>     
> threads = []    
> for _ in range(10):
>     thread = Thread(target=foo)
>     threads.append(thread)
> for _ in range(10):
>     thread = Thread(target=bar)
>     threads.append(thread)
>  
> for thread in threads:
>     thread.start()
> 
> for thread in threads:
>     thread.join()
> 
> 
> print(i)
> assert i == 0
> ```
> 
> 我是认为，这从侧面说明“Python还不是一个很稳定的语言”，像这种特性，无论是否是原子的，早就应该固定下来，不发生变化。

很有意思，3.10 的这个改动我也是第一次看到。这小部分内容我没有写进图书版里，如果之后修订，我考虑调整下措辞或示例来加强说服力。大观点会维持不变：不依赖任何直觉看上去像（未文档化的）“原子操作”的行为实现并发安全。
