### ISSUE TITLE
blog服务好像挂了.https://www.zlovezl.cn/

### ISSUE THREAD

**Issue by xie0723** [piglei/one-python-craftsman#52]
https://www.zlovezl.cn/   打不开！

**Comment by piglei** [comment]
这边测试正常打开。找了几个朋友、用工具测也可以呢。

**Comment by xie0723** [comment]
![image](https://user-images.githubusercontent.com/10458419/89272394-a6b85180-d670-11ea-97a9-1d30d5108ba2.png)


![image](https://user-images.githubusercontent.com/10458419/89272405-acae3280-d670-11ea-9300-fc815e8ee523.png)

---




让同事也试了下，也是打不开。😅

**Comment by longqzh** [comment]
@xie0723 Proxy Error....

**Comment by piglei** [comment]
我用手机 4G 网络测试也能正常打开，你用手机试试看？还有就是看看你们公司有没有啥特殊的代理配置？

话说我博客确实以前被墙过，有点心虚的很。😅

**Comment by xie0723** [comment]
昨天尝试4G是可以打开，但是办公网络还是无法打开。
但今天早上过来打开一切恢复正常了😅。
