### ISSUE TITLE
縮進問題

### ISSUE THREAD

**Issue by R0FGV** [piglei/one-python-craftsman#60]
在 做一个精通规则的玩家 這一節裏 的 利用集合的游戏规则這一小節  定義了VisitRecord 這個類，下面的__hash__  和__eq__兩個方法爲了是不是該有縮進，來匹配前文的語法結構

**Comment by piglei** [comment]
从正确性角度来说，是应该缩进的。但文章的那个位置本身只是用一小片代码表达那么个意思，所以没缩进问题也不大，先 close 了。
