### ISSUE TITLE
使用namedtuple可以用解包赋值给多个变量

### ISSUE THREAD

**Issue by vllbc** [piglei/one-python-craftsman#64]
` 不过这样做也有坏处，因为代码对变更的兼容性虽然变好了，但是你不能继续用之前 x, y = f() 的方式一次解包定义多个变量了。取舍在于你自己。 `
这句话不妥，使用namedtuple可以这么做

**Comment by piglei** [comment]
是的，有问题，感谢反馈。
目前在整体重写，这部分也会改掉。
