### ISSUE TITLE
第六篇文章“Write Cleaner Python: Use Exceptions”链接已失效

### ISSUE THREAD

**Issue by gotohx** [piglei/one-python-craftsman#66]
第六篇文章 [“Write Cleaner Python: Use Exceptions”]( https://github.com/piglei/one-python-craftsman/blame/master/zh_CN/6-three-rituals-of-exceptions-handling.md#L19) 链接已失效。

**Comment by piglei** [comment]
经查，已恢复（我也不知道啥时候恢复的）……
