### ISSUE TITLE
现已支持switch case

### ISSUE THREAD

**Issue by A100512B** [piglei/one-python-craftsman#67]

**Comment by A100512B** [comment]
在python 3.10中已经支持switch case，但是他在python里叫match case。
**使用 case _相当于Java中switch中的default子句**

**Comment by piglei** [comment]
感谢提醒，我确实也读过一些 Structural Pattern Matching 的相关介绍。

但在我目前正在进行的重写计划里，选用的主版本是 Python 3.8，所以暂时不会涉及到 Structural Pattern Matching。如果后续有变化，我会在这告诉你。
