### ISSUE TITLE
设计模式

### ISSUE THREAD

**Issue by madpudding** [piglei/one-python-craftsman#7]
你好，下一篇能否介绍一下python中常用到的设计模式呢，因为要构建高效的python代码，和适用合理的设计模式也分不开吧。

**Comment by piglei** [comment]
你好，没写设计模式，写了一篇和 OOP 相关的：https://github.com/piglei/one-python-craftsman/blob/master/zh_CN/12-write-solid-python-codes-part-1.md

这个 Issue 先关了哈。

**Comment by madpudding** [comment]
> 你好，没写设计模式，写了一篇和 OOP 相关的：https://github.com/piglei/one-python-craftsman/blob/master/zh_CN/12-write-solid-python-codes-part-1.md
> 
> 这个 Issue 先关了哈。

好的，谢谢你的付出。
