### ISSUE TITLE
底层看容器--3. 使用集合/字典来判断成员是否存在

### ISSUE THREAD

**Issue by FlyaOoo** [piglei/one-python-craftsman#8]
f-string的用法是3.6推出的，在文中多次提到3.5版本，对于新手可能不太友好，望采纳😄

**Comment by piglei** [comment]
你好，谢谢反馈。已添加说明。
https://github.com/piglei/one-python-craftsman/commit/c7b5099b3338b7a6ee0ce6c7eb1ba608bbdbb635
