### ISSUE TITLE
关于第三章里【常见误区】- 【字符串拼接并不慢】

### ISSUE THREAD

**Issue by hongkai98** [piglei/one-python-craftsman#82]
参考这篇文章 https://grski.pl/fstrings-performance.html

试了一下，好像结果最快的前四是f-string、join2、拼接、join1？

<img width="965" alt="image" src="https://user-images.githubusercontent.com/1357113/154826420-e225b504-c33f-46a2-9409-667fb14f2339.png">

**Comment by piglei** [comment]
是的，姑且可认为都在一个数量级。这也是我提出“如果需要字符串拼接，就拼接，不必担心性能问题”的原因。
