### ISSUE TITLE
书籍建议

### ISSUE THREAD

**Issue by hjlarry** [piglei/one-python-craftsman#83]
建议代码清单8-7和8-8中，使用`functools.update_wrapper`替换`update_wrapper`
一个是因为文章中并没有说update_wrapper是functools中的，还有就是8-8的代码中有用到`functools.partial`，应当统一

**Comment by piglei** [comment]
> 建议代码清单8-7和8-8中，使用`functools.update_wrapper`替换`update_wrapper` 一个是因为文章中并没有说update_wrapper是functools中的，还有就是8-8的代码中有用到`functools.partial`，应当统一

👍 你读的很细致。我检查了下，这块的处理的确实粗糙了，代码清单 8-7 的 import 语句也不应该省略。感谢反馈，有机会我会优化一下。

**Comment by hjlarry** [comment]
书已拜读完，受益匪浅，感谢

还发现两处小错误：
1. 书籍323页，`DIP认为客户依赖的接口不应该包含任何它不需要的方法`，应为`ISP`
2. 书籍340页，`按描实现方法的不同`，应为`按描述符方法的不通`

**Comment by piglei** [comment]
@hjlarry 不知你是否方便在图灵社区的[图书主页](https://www.ituring.com.cn/book/3007)上提交一下勘误，这样出版方比较容易跟进。感谢。
