### ISSUE TITLE
有关Monkey Patch

### ISSUE THREAD

**Issue by Jocker08** [piglei/one-python-craftsman#87]
请问朱雷老师对Monkey Patch是怎么看的？

**Comment by piglei** [comment]
Python 足够动态，所以靠 monkey patch 能完成很多天马行空的事情。据我所知，目前最成功、最广为人知的对 monkey patch 的应用还属 [gevent](http://www.gevent.org/) 。而对于普通项目来说，偶尔 patch 那么一两个第三方模块，达成一些特定目的，也很常见。但如果 patch 代码成吨出现，则可视为一种代码的“坏味道”，可以挖一挖，里面说不定藏匿着更深层的设计问题。

总之，单论 monkey patch 本身，我对它没什么值得一说的独到见解。

PS：前几天刚好逛到一个比较有特色的 patch 包，和普通的 monkey patch 很不一样。感兴趣的话可以了解下：

- [adamchainz/patchy: Patch the inner source of python functions at runtime.](https://github.com/adamchainz/patchy)
