### ISSUE TITLE
是否有epub电子书购买渠道？

### ISSUE THREAD

**Issue by JisongXie** [piglei/one-python-craftsman#88]
您好，请问能否有epub格式的电子书购买渠道？目前看到的只有纸质书。我是ibook用户，习惯使用epub格式的电子书。

**Comment by piglei** [comment]
你好，[图灵图书主页](https://www.ituring.com.cn/book/details/3007) 可以购买 mobi 格式，
再借助 Calibre 等工具，就能转换成 epub 了。

**Comment by JisongXie** [comment]
感谢
