### ISSUE TITLE
On Code Repo

### ISSUE THREAD

**Issue by LordMoMA** [piglei/one-python-craftsman#90]
Hi Lei,

I quite enjoy reading your book. I wonder if your one-python-craftsman book has a repo for all the code examples in the book like Fluent Python: https://github.com/fluentpython/example-code-2e 

Thank you for the help,

**Comment by piglei** [comment]
Yes, you can find all the code snippets in [this repository](https://github.com/piglei/the-python-craftsman-book).

**Comment by LordMoMA** [comment]
Thank you very much ;)
