### ISSUE TITLE
类型注解来声明类型

### ISSUE THREAD

**Issue by Routhleck** [piglei/one-python-craftsman#93]
在第一章中，或许可以在[变量名最好让人能猜出类型](https://github.com/piglei/one-python-craftsman/blob/master/zh_CN/1-using-variables-well.md#2-%E5%8F%98%E9%87%8F%E5%90%8D%E6%9C%80%E5%A5%BD%E8%AE%A9%E4%BA%BA%E8%83%BD%E7%8C%9C%E5%87%BA%E7%B1%BB%E5%9E%8B)里介绍下使用类型注解来声明类型和函数返回值，能够提升代码可读性、更好维护

**Comment by piglei** [comment]
你好，我在重写图书版《Python工匠》时，调整过这部分表达，[详见这里](https://www.piglei.com/book/ch01_variables.html#_4_%E8%A6%81%E5%8C%B9%E9%85%8D%E7%B1%BB%E5%9E%8B)。此外在书中第 10 章，我对 Python 的类型注解功能也做了简单的介绍。

如果你是从头开始阅读《Python工匠》，建议直接读图书版，内容更丰富。
